# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Desktop/cpu/cpu.cache/wt [current_project]
set_property parent.project_path D:/Desktop/cpu/cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.2 [current_project]
read_verilog -library xil_defaultlib D:/Desktop/cpu/cpu.srcs/sources_1/new/cpu.v
synth_design -top cpu -part xc7a200tfbg676-2
write_checkpoint -noxdef cpu.dcp
catch { report_utilization -file cpu_utilization_synth.rpt -pb cpu_utilization_synth.pb }
